from flask import Flask, render_template, jsonify
from mysql import db 
app = Flask(__name__)
app.config.from_object('config')
with app.app_context(): 
   db.init_app(app)
   db.drop_all()
   db.create_all()
   admin_role=Role(name='Admin') 
   mod_role = Role(name='Moderator') 
   user_role = Role(name='User') 
   user_john = User(username='john', role_id=admin_role) 
   user_susan = User(username='susan', role_id=user_role) 
   user_david = User(username='david', role_id=user_role)
   db.session.add(admin_role) 
   db.session.add(mod_role) 
   db.session.add(user_role) 
   db.session.add(user_john) 
   db.session.add(user_susan) 
   db.session.add(user_david)
   db.session.commit()