"""initial migration

Revision ID: f9edd69fcb9d
Revises: a04fff14569d
Create Date: 2019-03-26 22:07:52.119721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9edd69fcb9d'
down_revision = 'a04fff14569d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('性别', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_users_性别'), 'users', ['性别'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_性别'), table_name='users')
    op.drop_column('users', '性别')
    # ### end Alembic commands ###
